# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Swiss Film Academy of New York
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Swiss Film Academy of New York is a nonprofit film school located in
  Manhattan, New York, founded in 2017 by Educasuisse located in Geneva,
  Switzerland. The School offers noncredit courses in the arts of filmmaking,
  producing, directing and screenwriting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swissfilm-academy.nyc" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
